app/app/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('',include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/',include(('inv.urls', 'inv'), namespace='inv')),
    path('cli/',include(('cli.urls', 'cli'), namespace='cli')),
    #path('cmp/',include(('cmp.urls', 'cmp'), namespace='cmp')),
    
    path('admin/', admin.site.urls),

]

app/inv/urls.py
from django.urls import path


from .views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaDel, \
    ProductoView, ProductoNew, ProductoEdit, producto_inactivar
    

urlpatterns = [
    path('categorias/' , CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new' , CategoriaNew.as_view(), name='categoria_new'),
    path('categorias/edit/<int:pk>' , CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/delete/<int:pk>' , CategoriaDel.as_view(), name='categoria_del'),

    path('productos/' , ProductoView.as_view(), name='producto_list'),
    path('productos/new' , ProductoNew.as_view(), name='producto_new'),
    path('productos/edit/<int:pk>' , ProductoEdit.as_view(), name='producto_edit'),
    path('productos/inactivar/<int:id>' , producto_inactivar, name='producto_inactivar'),

    
]

app/bases/models.py
from abc import abstractmethod
from django.db import models

from django.contrib.auth.models import User

class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    modified_by = models.IntegerField(blank=True, null=True)
    
    class Meta:
        abstract =True

# Create your models here.

app/inv/models.py
from enum import unique
from django.db import models

from bases.models import ClaseModelo

class Categoria(ClaseModelo):
    descripcion = models.CharField(max_length=100, help_text='Descripción de la categoría', unique=True)

    def __str__(self) :
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save()

    class Meta:
        verbose_name_plural="Categorias"

#PRODUCTO        

class Producto(ClaseModelo):
    codigo= models.CharField(max_length=20, unique=True)
    codigo_barra = models.CharField(max_length=200)
    descripcion = models.CharField(max_length=200)
    precio = models.FloatField(default=0)
    existencia = models.IntegerField(default=0)
    ultima_compra = models.DateField(null=True, blank=True)

    #marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    #u_medida = models.ForeignKey(UM, on_delete=models.CASCADE)
    #subcategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE)

    def __str__(self) :
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Producto, self).save()

    class Meta:
        verbose_name_plural="Productos"
        unique_together =('codigo', 'codigo_barra')

app/inv/forms.py
from django import forms
#from django.db import models
#from django.forms import fields, widgets
from .models import Categoria, Producto


class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['descripcion', 'estado']
        labels = {'descripcion': "Descripcion de la Categoria",
                'estado': "Estado"}
        widget = {'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
        
#PRODUCTO----------------------------------------------------------

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        #fields = ['codigo','codigo_barra','descripcion', 'estado', 'precio', 'existencia','ultima_compra', 'marca','subcategoria', 'u_medida']
        fields = ['codigo','codigo_barra','descripcion', 'estado', 'precio', 'existencia','ultima_compra']
        exclude =['created_date','modified_date','created_by' ,'modified_by']
        widget = {'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
        self.fields['ultima_compra'].widget.attrs['readonly'] = True
        self.fields['existencia'].widget.attrs['readonly'] = True

app/inv/views.py
from typing import Generic
from django.shortcuts import  render, redirect
from django.urls.base import reverse_lazy

from django.views import generic

# Create your views here.

from django.contrib.auth.mixins import LoginRequiredMixin


from .models import Categoria, Producto
from .forms import CategoriaForm, ProductoForm

class CategoriaView(LoginRequiredMixin, generic.ListView):
    model = Categoria
    template_name = "inv/categoria_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'

class CategoriaNew(LoginRequiredMixin, generic.CreateView):
    model = Categoria
    template_name = "inv/categoria_form.html"
    context_object_name = "obj"
    form_class = CategoriaForm
    success_url =reverse_lazy("inv:categoria_list")
    login_url = 'bases:login'

    def form_valid(self, form):
        form.instance.created_by = self.request.user 
        return super().form_valid(form)

class CategoriaEdit(LoginRequiredMixin, generic.UpdateView):
    model = Categoria
    template_name = "inv/categoria_form.html"
    context_object_name = "obj"
    form_class = CategoriaForm
    success_url =reverse_lazy("inv:categoria_list")
    login_url = 'bases:login'

    def form_valid(self, form):
        form.instance.modified_by = self.request.user.id
        return super().form_valid(form)
    
class CategoriaDel(LoginRequiredMixin, generic.DeleteView):
    model = Categoria
    template_name = "inv/catalogos_del.html"
    context_object_name = "obj"    
    success_url =reverse_lazy("inv:categoria_list")

# PRODUCTO---------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------

class ProductoView(LoginRequiredMixin, generic.ListView):
    model = Producto
    template_name = "inv/producto_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'

class ProductoNew(LoginRequiredMixin, generic.CreateView):
    model = Producto
    template_name = "inv/producto_form.html"
    context_object_name = "obj"
    form_class = ProductoForm
    success_url =reverse_lazy("inv:producto_list")
    login_url = 'bases:login'

    def form_valid(self, form):
        form.instance.created_by = self.request.user 
        return super().form_valid(form)

class ProductoEdit(LoginRequiredMixin, generic.UpdateView):
    model = Producto
    template_name = "inv/producto_form.html"
    context_object_name = "obj"
    form_class = ProductoForm
    success_url =reverse_lazy("inv:producto_list")
    login_url = 'bases:login'

    def form_valid(self, form):
        form.instance.modified_by = self.request.user.id
        return super().form_valid(form)
    
def producto_inactivar(request, id):
    producto = Producto.objects.filter(pk=id).first()
    contexto={}
    template_name="inv/catalogos_del.html"

    if not producto:
        return redirect("inv:producto_list")

    if request.method == 'GET':
        contexto = {'obj' :producto}
    
    if request.method == 'POST':
        producto.estado=False
        producto.save()
        return redirect("inv:producto_list")

    return render(request, template_name, contexto)

app/inv/templates/inv/catalogos_del.html
{% extends 'base/base.html' %}

{% block page_content %}
<form method="POST" class="form-inline">
    {% csrf_token %}
    <!-- Pending Requests Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-danger shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1"></i>¿Eliminar {{obj.descripcion}}?</div>
                        <button type="submit" class="btn btn-danger"><i class="far fa-question-circle"></i>Si, eliminar</button>
                        <!-- <a href="{% url 'inv:categoria_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a> -->
                        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-question-circle fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}
{ % block js_page% }
{ % endblock%}

app/inv/templates/inv/categoria_form.html
{% extends 'base/base.html' %}

{% block page_content %}
<form method="POST" class="form-inline">
    {% csrf_token %}
    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-6 col-md-6 mb-6">
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
        {% else %}
        <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            {% if obj %} Editar {% else %} Nueva {% endif %} categoria
                        </div>
                        
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col-10">
                                <div class="input-group">
                                    <input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" 
                                    placeholder="Descripción" 
                                    value="{% if obj %} {{obj.descripcion}} {% endif %} ">
                                </div>
                            </div>

                            <div class="col-2">
                                <div class="form-group">
                                    <label for="id_estado">Estado</label>
                                    <input type="checkbox" name="estado" class="form-control" id="id_estado"
                                    {% if obj.estado %} checked {% endif %}>
                                </div>
                            </div>
                            <!-- {{form.as_p}}-->
                        </div>   

                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"> <span class="fa fa-save"></span>Guardar</button>
                                <a href="{% url 'inv:categoria_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                            </div>
                        </div>


                    </div>
                    <div class="col-auto">
                        <i class="far fa-calendar fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}
{ % block js_page% }
{ % endblock%}

app/inv/templates/inv/categoria_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div
        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de Categorias</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones</div>
                <a class="dropdown-item" href="{% url 'inv:categoria_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
           <div class="alert alert-info">No hay Categorias</div>
        {% else %}
        <table class="table table-striped table-hover">
            <thead>
                <th>Id</th>
                <th>Descripción</th>
                <th>Estado</th>
                <th>Fecha Creación</th>
                <th>Fecha Modificación</th>
                <th class="all">Acciones</th>
            </thead>
            <tbody>
                {%  for item in obj %}
                <tr>
                    <td>{{ item.id}}</td>
                    <td>{{ item.descripcion}}</td>
                    <td>{{ item.estado|yesno:"Activo,Inactivo"}}</td>
                    <td>{{ item.created_date|date:"d/m/Y H:i:s" }}</td>
                    <td>{{ item.modified_date|date:"d/m/Y H:i:s"}}</td>
                    <td>
                        <a href="{% url 'inv:categoria_edit' item.id %}" class="btn btn-warning btn-circle" role="button"> <i class="far fa-edit"></i></a>
                        <a href="{% url 'inv:categoria_del' item.id %}" class="btn btn-danger btn-circle" role="button"> <i class="far fa-trash-alt"></i></a>
                    </td>
                </tr>
                {% endfor %}

            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block js_page %}
<script>
// Call the dataTable JQuery plugin
$(document).ready(function() {
    $('.table').DataTable();
});
</script>
{% endblock %}

app/inv/templates/inv/producto_form.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        {% if obj %}
        <form method="POST" role="form" class="form-inline" action="{% url 'inv:producto_edit' obj.pk %}" enctype="multipart/form-data" >
        {% else %}
        <form method="POST" role="form" class="form-inline" action="{% url 'inv:producto_new' %}"  enctype="multipart/form-data" >
        {% endif %}
            <div class="col-xl-12 col-md-12 mb-12">
                {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            {% if obj %} Editar {% else %} Nueva {% endif %} Producto
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            {{ form.as_p }}
                        </div>

                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                                
                                <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                    Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    $(function() {
        $("#id_categoria").val("{{ obj.subcategoria.categoria.id }}").change();
        $("#id_subcategoria").val("{{ obj.subcategoria.id }}").change();
        $("#id_subcategoria").chained("#id_categoria");
    });
</script>

app/inv/templates/inv/producto_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div
        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de Productos</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones</div>
                <a class="dropdown-item" onclick="return abrir_modal('{% url 'inv:producto_new' %}')" href=""><i class="far fa-calendar-plus"></i> Nuevo</a>
                
            </div>
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
           <div class="alert alert-info">No hay Productos</div>
        {% else %}
        <table class="table table-striped table-hover">
            <thead>
                
                <th>Código</th>
                <th>Barra</th>
                <th>Descripcion</th>
                <th>Existencia</th>
                <th>Precio</th>
                <th>Estado</th>
                <th class="all">Acciones</th>
            </thead>
            <tbody>
                {%  for item in obj %}
                <tr>
                    
                    <td>{{ item.codigo }}</td>
                    <td>{{ item.codigo_barra }}</td>
                    <td>{{ item.descripcion }}</td>
                    <td>{{ item.existencia }}</td>
                    <td>{{ item.precio }}</td>
                    <td>{{ item.estado|yesno:"Activo,Inactivo"}}</td>

                    <td>
                        <button class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'inv:producto_edit' item.id %}')" >
                            <i class="far fa-edit"></i></button>
                            <a href="{% url 'inv:producto_inactivar' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-thumbs-down"></i></a>
                    </td>
                </tr>
                {% endfor %}

            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block js_page %}
<script>
// Call the dataTable JQuery plugin
$(document).ready(function() {
    $('.table').DataTable();
});
</script>
{% endblock %}