app/app/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('',include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/',include(('inv.urls', 'inv'), namespace='inv')),
    path('cli/',include(('cli.urls', 'cli'), namespace='cli')),
    #path('cmp/',include(('cmp.urls', 'cmp'), namespace='cmp')),
    
    path('admin/', admin.site.urls),

]

app/cli/urls.py
from django.urls import path


from .views import ClienteView, ClienteNew, ClienteEdit, cliente_inactivar
    

urlpatterns = [

    path('Clientes/' , ClienteView.as_view(), name='cliente_list'),
    path('Clientes/new' , ClienteNew.as_view(), name='cliente_new'),
    path('Clientes/edit/<int:pk>' , ClienteEdit.as_view(), name='cliente_edit'),
    path('Clientes/inactivar/<int:id>' , cliente_inactivar, name='cliente_inactivar'),

    
]

app/inv/urls.py
from django.urls import path


from .views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaDel, \
    ProductoView, ProductoNew, ProductoEdit, producto_inactivar
    

urlpatterns = [
    path('categorias/' , CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new' , CategoriaNew.as_view(), name='categoria_new'),
    path('categorias/edit/<int:pk>' , CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/delete/<int:pk>' , CategoriaDel.as_view(), name='categoria_del'),

    path('productos/' , ProductoView.as_view(), name='producto_list'),
    path('productos/new' , ProductoNew.as_view(), name='producto_new'),
    path('productos/edit/<int:pk>' , ProductoEdit.as_view(), name='producto_edit'),
    path('productos/inactivar/<int:id>' , producto_inactivar, name='producto_inactivar'),

    
]

app/cli/models.py
from enum import unique
from django.db import models

from bases.models import ClaseModelo


#CLIENTE       

class Cliente(ClaseModelo):
    codigo= models.CharField(max_length=20, unique=True)
    rut = models.CharField(max_length=200)
    nombres = models.CharField(max_length=200)
    apellidos = models.CharField(max_length=200)
    direccion = models.CharField(max_length=200)
    fecha_nac = models.DateField(null=True, blank=True)
    
    #precio = models.FloatField(default=0)
    #existencia = models.IntegerField(default=0)
    #marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    #u_medida = models.ForeignKey(UM, on_delete=models.CASCADE)
    #subcategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE)

    def __str__(self) :
        return '{}'.format(self.rut)

    def save(self):
        self.rut = self.rut.upper()
        super(Cliente, self).save()

    class Meta:
        verbose_name_plural="Clientes"
        unique_together =('codigo', 'rut')

app/cli/forms.py
from django import forms
#from django.db import models
#from django.forms import fields, widgets
from .models import Cliente


class ClienteForm(forms.ModelForm):
    fecha_nac = forms.DateInput()
    class Meta:
        model = Cliente
        fields = ['codigo','rut','nombres', 'apellidos', 'direccion', 'fecha_nac','estado']
        exclude =['created_date','modified_date','created_by' ,'modified_by']
        widget = {'rut': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
        #self.fields['ultima_compra'].widget.attrs['readonly'] = True
        #self.fields['existencia'].widget.attrs['readonly'] = True

app/cli/views.py
from typing import Generic
from django.shortcuts import  render, redirect
from django.urls.base import reverse_lazy

from django.views import generic

# Create your views here.

from django.contrib.auth.mixins import LoginRequiredMixin


from .models import Cliente
from .forms import ClienteForm

class ClienteView(LoginRequiredMixin, generic.ListView):
    model = Cliente
    template_name = "cli/cliente_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'

class ClienteNew(LoginRequiredMixin, generic.CreateView):
    model = Cliente
    template_name = "cli/cliente_form.html"
    context_object_name = "obj"
    form_class = ClienteForm
    success_url =reverse_lazy("cli:cliente_list")
    login_url = 'bases:login'

    def form_valid(self, form):
        form.instance.created_by = self.request.user 
        return super().form_valid(form)

class ClienteEdit(LoginRequiredMixin, generic.UpdateView):
    model = Cliente
    template_name = "cli/cliente_form.html"
    context_object_name = "obj"
    form_class = ClienteForm
    success_url =reverse_lazy("cli:cliente_list")
    login_url = 'bases:login'

    def form_valid(self, form):
        form.instance.modified_by = self.request.user.id
        return super().form_valid(form)
    
def cliente_inactivar(request, id):
    cliente = Cliente.objects.filter(pk=id).first()
    contexto={}
    template_name="cli/cliente_del.html"

    if not cliente:
        return redirect("cli:cliente_list")

    if request.method == 'GET':
        contexto = {'obj' :cliente}
    
    if request.method == 'POST':
        cliente.estado=False
        cliente.save()
        return redirect("cli:cliente_list")

    return render(request, template_name, contexto)

app/cli/templates/cli/cliente_del.html
{% extends 'base/base.html' %}

{% block page_content %}
<form method="POST" class="form-inline">
    {% csrf_token %}
    <!-- Pending Requests Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-danger shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1"></i>¿Eliminar {{obj.rut}}?</div>
                        <button type="submit" class="btn btn-danger"><i class="far fa-question-circle"></i>Si, eliminar</button>
                        <!-- <a href="{% url 'inv:categoria_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a> -->
                        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-question-circle fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}
{ % block js_page% }
{ % endblock%}

app/cli/templates/cli/cliente_form.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        {% if obj %}
        <form method="POST" role="form" class="form-inline" action="{% url 'cli:cliente_edit' obj.pk %}" enctype="multipart/form-data" >
        {% else %}
        <form method="POST" role="form" class="form-inline" action="{% url 'cli:cliente_new' %}"  enctype="multipart/form-data" >
        {% endif %}
            <div class="col-xl-12 col-md-12 mb-12">
                {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            {% if obj %} Editar {% else %} Nueva {% endif %} cliente
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            {{ form.as_p }}
                        </div>

                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                                
                                <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                    Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    $(function() {
        $("#id_categoria").val("{{ obj.subcategoria.categoria.id }}").change();
        $("#id_subcategoria").val("{{ obj.subcategoria.id }}").change();
        $("#id_subcategoria").chained("#id_categoria");
    });
</script>

app/cli/templates/cli/cliente_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div
        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de Clientes</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones</div>
                <a class="dropdown-item" onclick="return abrir_modal('{% url 'cli:cliente_new' %}')" href=""><i class="far fa-calendar-plus"></i> Nuevo</a>
                
            </div>
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
           <div class="alert alert-info">No hay Clientes</div>
        {% else %}
        <table class="table table-striped table-hover">
            <thead>
                
                <th>Código</th>
                <th>Rut</th>
                <th>nombres</th>
                <th>apellidos</th>
                <th>direccion</th>
                <th>F Nac</th>
                <th>Estado</th>
                <th class="all">Acciones</th>
            </thead>
            <tbody>
                {%  for item in obj %}
                <tr>
                    
                    <td>{{ item.codigo }}</td>
                    <td>{{ item.rut }}</td>
                    <td>{{ item.nombres }}</td>
                    <td>{{ item.apellidos }}</td>
                    <td>{{ item.direccion }}</td>
                    <td>{{ item.fecha_nac|date:"d/m/Y" }}</td>
                    <td>{{ item.estado|yesno:"Activo,Inactivo"}}</td>

                    <td>
                        <button class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'cli:cliente_edit' item.id %}')" >
                            <i class="far fa-edit"></i></button>
                            <a href="{% url 'cli:cliente_inactivar' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-thumbs-down"></i></a>
                    </td>
                </tr>
                {% endfor %}

            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block js_page %}
<script>
// Call the dataTable JQuery plugin
$(document).ready(function() {
    $('.table').DataTable();
});
</script>
{% endblock %}